// <auto-generated />
using System;

using AppBroker.Core.Database;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBroker.Core.Database.Migrations.BrokerDb
{
    [DbContext(typeof(BrokerDbContext))]
    [Migration("20220923182626_AddedLastState")]
    partial class AddedLastState
    {
    }
}
