// <auto-generated />
using System;
using AppBroker.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBroker.Core.Database.Migrations.BrokerDb
{
    [DbContext(typeof(BrokerDbContext))]
    partial class BrokerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("AppBroker.Core.Database.Model.DeviceMappingModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("DeviceToDeviceMappings");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.DeviceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeserializationData")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyUniqueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastState")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastStateChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartAutomatically")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.GroupDeviceMappingModel", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId", "GroupId");

                    b.ToTable("GroupDeviceMappingModels");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.GroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroupModels");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.HeaterConfigModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeatingPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<long>("TimeOfDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("HeaterConfigs");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.HeatingPlanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HeatingPlanModels");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.DeviceMappingModel", b =>
                {
                    b.HasOne("AppBroker.Core.Database.Model.DeviceModel", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId");

                    b.HasOne("AppBroker.Core.Database.Model.DeviceModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.HeaterConfigModel", b =>
                {
                    b.HasOne("AppBroker.Core.Database.Model.DeviceModel", "Device")
                        .WithMany("HeaterConfigs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AppBroker.Core.Database.Model.DeviceModel", b =>
                {
                    b.Navigation("HeaterConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
