// <auto-generated />
using System;
using System.ComponentModel.DataAnnotations.Schema;

using AppBroker.Core.Database.History;


using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBroker.Core.Database.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20220918143339_HeaterConfigs")]
    partial class HeaterConfigs
    {

    }
}
