// <auto-generated />
using AppBroker.Core.Database.History;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBroker.Core.Database.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20230401133729_HistoryIndex")]
    partial class HistoryIndex
    {
       
    }
}
