// <auto-generated />
using System;

using AppBroker.Core.Database.History;


using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBroker.Core.Database.AppDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration(Id)]
    partial class InitialCreate 
    {
        public const string Id = $"20240509175553_InitialCreate";

    }
}
