name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Git Submodules
        run: git submodule update --init --recursive
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}
          
      - name: Build AppBroker and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: AppBrokerASP/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/susch19/appbroker:latest
          labels: ${{ steps.meta.outputs.labels }}
          
      # - name: Build TCPProxy and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm/v7,linux/arm64
      #     file: TcpProxy/Dockerfile
      #     push: true
      #     tags: ghcr.io/susch19/appbroker-tcpproxy:${{ github.event.inputs.tag }}
      #     labels: ${{ steps.meta.outputs.labels }}
          
